name: hemovision
description: "OmniSight Engine - Vision to Audio and Audio to Vision for Accessibility"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  camera: ^0.10.6
  vibration: ^2.0.0
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
